services:
  redis:
    image: redis:alpine
    container_name:  monorepo-redis
    hostname: redis
    ports:
      - '${PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: monorepo-network
    external: true
